# This is a basic workflow to help you get started with Actions

name: Build Docker container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build minimal container
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build Docker container
      run: |
        docker build -f Dockerfile2 -t cwuensch/vs2010:minimal .
      
    - name: Push Docker container 
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push cwuensch/vs2010:minimal

  test:
    name: Test minimal container
    runs-on: windows-2019
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}/RS:C:/source/ --workdir "C:/source" cwuensch/vs2010:minimal /m /p:Configuration=Release /p:Platform=Win32 C:\source\RecStrip_VS\RecStrip.sln
        docker run --rm -v ${{ github.workspace }}/RS:C:/source/ --workdir "C:/source" cwuensch/vs2010:minimal /m /p:Configuration=Release /p:Platform=x64 C:\source\RecStrip_VS\RecStrip.sln
