# This is a basic workflow to help you get started with Actions

name: Build Mini container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ minimal ]
  pull_request:
    branches: [ minimal ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build minimal container
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker container
      run: |
        docker build -f Dockerfile -t cwuensch/vs2010:minimal .
      
    - name: Push Docker container 
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push cwuensch/vs2010:minimal

  test:
    name: Test minimal container
    runs-on: windows-2019
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: cwuensch/RecStrip
#        ref: refs/heads/release

    - name: Start Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:C:/source/ --workdir "C:/source" cwuensch/vs2010:minimal /m /p:Configuration=Release /p:Platform=Win32 RecStrip_VS/RecStrip.sln
        docker run --rm -v ${{ github.workspace }}:C:/source/ --workdir "C:/source" cwuensch/vs2010:minimal /m /p:Configuration=Release /p:Platform=x64 RecStrip_VS/RecStrip.sln

    - name: Rename compiled files
      run: |
        move "RecStrip_VS\Release\RecStrip.exe" "RecStrip_VS\RecStrip_Win32.exe"
        move "RecStrip_VS\x64\Release\RecStrip.exe" "RecStrip_VS\RecStrip_x64.exe"

    - name: Copy build artefact
      uses: actions/upload-artifact@v2
      with:
        name: RecStrip_Windows
        path: |
          ${{ github.workspace }}/RecStrip_VS/RecStrip_Win32.exe
          ${{ github.workspace }}/RecStrip_VS/RecStrip_x64.exe
